- name: Setup Scylla
  hosts: raft_demo
  connection: local
  tasks:
    - name: create configuration folder
      ansible.builtin.file:
        path: "{{scylla_home}}/conf"
        state: directory
    - name: create configuration file
      ansible.builtin.template:
        src: scylla.yaml
        dest: "{{scylla_home}}/conf/scylla.yaml"
    - name: create commitlog folder
      ansible.builtin.file:
        path: "{{scylla_home}}/commitlog"
        state: directory
    - name: create data folder
      ansible.builtin.file:
        path: "{{scylla_home}}/data"
        state: directory
    - name: create hints folder
      ansible.builtin.file:
        path: "{{scylla_home}}/hints"
        state: directory
    - name: create view_hints folder
      ansible.builtin.file:
        path: "{{scylla_home}}/view_hints"
        state: directory
    - name: copy start script
      ansible.builtin.template:
        src: start.sh
        dest: "{{scylla_home}}"
        mode: a+x
    - name: report status
      debug:
        msg: "Done setting up {{ inventory_hostname }}."
